### ISSUE TITLE
ada error

### ISSUE THREAD

**Issue by aviqbaihaqy** [panada/http#1]
script method set nya:

``` PHP
public function set(){
        $this->session->setValue('isLogin',true);
        $this->session->setValue('name','foo');
        return $this->response->redirect('admin');
    }
```

![screenshot_2](https://cloud.githubusercontent.com/assets/1930221/11519599/2008efbc-98ce-11e5-9e67-977be5c26dad.png)

**Comment by ikandars** [comment]
yang ini sudah di fix di sini ya mas https://github.com/panada/http/commit/ccda002e05110a299b8292edaee09aac352af944 silahkan jalankan:

```
composer update
```
